### ISSUE TITLE
Error on preprocess_features.py

### ISSUE THREAD

**Issue by elliotnam** [davek44/Basset#1]
Hi
when I run preprocess_features.py
I got out of index error from line 76

['>chr1']
Traceback (most recent call last):
  File "./preprocess_features.py", line 420, in <module>
    main()
  File "./preprocess_features.py", line 76, in main
    chrom_lengths[a[0]] = int(a[1])
IndexError: list index out of range

so I printed a and the result is 
['>chr1']

Is there anythin I missed
thx

**Comment by davek44** [comment]
Hi,

It appears that the program is examining a FASTA file where it expects a file containing a table with two columns. The first column should have the chromosome name, like "chr1". The second column should have the length of the chromosome. It's the "-c" option that specifies the path to this file. If you're not able to figure out why your command doesn't work, print it here, and I'll give you a hand.

Dave

**Comment by elliotnam** [comment]
Hi
I run this command

preprocess_features.py -y -m 200 -s 600 -o ../data/encode_roadmap -c
../data/genomes/hg19.fa ../data/sample_beds.txt

and i checked the file hg19.fa , on the first column, I found chr1 but
there is no length
like this
>chr1
NNNNNNNNNNNNNNNNNNNNNNNN

Do I have wrong data file ?

2015-10-08 22:38 GMT+09:00 David Kelley <notifications@github.com>:

**Comment by davek44** [comment]
Yes, you'll want to provide the file human.hg19.genome in the directory data/genomes to the -c option.

**Comment by davek44** [comment]
Ah, I see that the tutorial specified the wrong file. I corrected the error.
