### ISSUE TITLE
Use docstrings for function comments

### ISSUE THREAD

**Issue by hammer** [davek44/Basset#10]
You've done a great job documenting functions but by putting them in comments rather than docstrings they're not available to users interactively.

**Comment by hammer** [comment]
For bonus points, follow the [Google style guide](http://sphinxcontrib-napoleon.readthedocs.org/en/latest/example_google.html#example-google) for the docstrings.

**Comment by davek44** [comment]
Great tip! I only recently learned about this, so most are proper but there's still a bunch of stragglers. Will fix that up soon.
