### ISSUE TITLE
basset_sad fails with wrong matching to reference genome

### ISSUE THREAD

**Issue by wormsik** [davek44/Basset#16]
When using `basset_sad.py` with the input vcf file containing wrong mappings of reference allele to reference genome, the script at first prints warning message:

`WARNING: skipping 10100 because reference allele does not match reference genome: G vs A`

but after a while the calculation fails with this exception:

```
Traceback (most recent call last):
  File "/software/basset/src/basset_sad.py", line 216, in <module>
    main()
  File "/software/basset/src/basset_sad.py", line 111, in main
    ref_preds = seq_preds[pi,:]
IndexError: index 1998 is out of bounds for axis 0 with size 1998
```

When I remove the wrong line from input file, calculation is completed successfully. 
I don't know if this is desired behavior, but I suggest to terminate the calculation as soon as possible (if it is not possible to recover from this error).

**Comment by davek44** [comment]
Good point. I'm exiting now. I'll look into whether I can make it more robust to alleles that don't match. I'm new to genetics data, so I don't fully understand why it wouldn't match.
