### ISSUE TITLE
bedtools is a dependency for install_data.py

### ISSUE THREAD

**Issue by vjcitn** [davek44/Basset#17]
it may seem strange for a user in this space to lack bedtools, but it can happen...

https://www.dropbox.com/s/h1cqokbr8vjj5wc/encode_roadmap.bed.gz: HTTPS support not compiled in.
gunzip: can't stat: encode_roadmap.bed.gz (encode_roadmap.bed.gz.gz): No such file or directory
https://www.dropbox.com/s/8g3kc0ai9ir5d15/encode_roadmap_act.txt.gz: HTTPS support not compiled in.
gunzip: can't stat: encode_roadmap_act.txt.gz (encode_roadmap_act.txt.gz.gz): No such file or directory
/bin/sh: bedtools: command not found

**Comment by davek44** [comment]
It's already on the list https://github.com/davek44/Basset/blob/master/docs/requirements.md

Those files don't appear to have downloaded either. Do you know why that didn't work?

**Comment by davek44** [comment]
Oops I see you posted that as another issue. I'll address it there.

**Comment by vjcitn** [comment]
Apropos bedtools: yes, it is on the full requirement list, but the text in
README.md says you only
need to check the full requirements list if you don't use anaconda.  Minor
issue of course.

**Comment by davek44** [comment]
Good point. I added it to the README. Thanks!
