### ISSUE TITLE
should check whether wget is adequate for retrievals in install_data.py

### ISSUE THREAD

**Issue by vjcitn** [davek44/Basset#18]
install_data.py moves along but eventually ...

https://www.dropbox.com/s/h1cqokbr8vjj5wc/encode_roadmap.bed.gz: HTTPS support not compiled in.
gunzip: can't stat: encode_roadmap.bed.gz (encode_roadmap.bed.gz.gz): No such file or directory
https://www.dropbox.com/s/8g3kc0ai9ir5d15/encode_roadmap_act.txt.gz: HTTPS support not compiled in.

one way to solve is to build wget from source with openssl ... links and details here:
https://coolestguidesontheplanet.com/install-and-configure-wget-on-os-x/

**Comment by davek44** [comment]
Thanks for the note. I made it switch to use curl if the user doesn't have wget.
