### ISSUE TITLE
install_dependencies.py fails on macosx

### ISSUE THREAD

**Issue by vjcitn** [davek44/Basset#19]
there is a stream of errors of this type.

%vjcair> ./install_dependencies.py
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/torch/rocks/master - Failed downloading https://raw.githubusercontent.com/torch/rocks/master/manifest - /Users/stvjc/.cache/luarocks/https___raw.githubusercontent.com_torch_rocks_master/manifest
Warning: Failed searching manifest: Failed fetching manifest for https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master - Failed downloading https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/manifest - /Users/stvjc/.cache/luarocks/https___raw.githubusercontent.com_rocks-moonscript-org_moonrocks-mirror_master/manifest

such an error can be found on the web and the proposed solution is to remove ~/.cache/luarocks but this does not rectify in this case.  we have such errors as

Error: No results matching query were found.
fatal: destination path 'torch-hdf5' already exists and is not an empty directory.

Missing dependencies for hdf5:
totem 

Error: Could not satisfy dependency: totem 

To attempt to deal with totem, I used

    curl https://raw.githubusercontent.com/deepmind/torch-totem/master/rocks/totem-0-0.rockspec -o totem-0-0.rockspec
    sudo luarocks install totem-0-0.rockspec

this seems to have worked.

**Comment by davek44** [comment]
This one's beyond my software installation capabilities. Sorry
