### ISSUE TITLE
can't find the file 

### ISSUE THREAD

**Issue by kwangjun14** [davek44/Basset#2]
Hi
When I run this  comnand 
!cd ../data; preprocess_features.py -y -m 200 -s 600 -o er -c genomes/human.hg19.genome sample_beds.txt

I got an error because there is no human.hg19.genome under genomes directory, there are 
hg19.fa, hg19fa.fai files,  How can I get  the human.hg19.genome file or I  missed  something ?

**Comment by davek44** [comment]
The file is there. See: https://github.com/davek44/Basset/blob/master/data/genomes/human.hg19.genome
