### ISSUE TITLE
last layer

### ISSUE THREAD

**Issue by shayanshams66** [davek44/Basset#24]
Hi,
I am trying to find what you guys used for the last layer function? is it softmax or any specific function. I tried to go through the codes but I couldnt find how did you implement the last layer ?
can you please help me with that and also tell me where I can find the detailed code implementation please?
Thanks in advance

**Comment by davek44** [comment]
The typical case is a multi-task binary classification problem. So the default final layer applies a sigmoid transformation to offer a vector of 0-1 values that can roughly be interpreted as the probability of accessibility/binding/activity/whatever in each of the experiments given.

However, there are some other options coded up in there, for example for regression. You can see them here: https://github.com/davek44/Basset/blob/master/src/convnet.lua#L55-L72
