### ISSUE TITLE
Output name of basset_sat_vcf.py

### ISSUE THREAD

**Issue by dborgesr** [davek44/Basset#26]
Hey,
So the output of basset_sat_vcf often times includes ">" in the file output name, that breaks it. Just gotta add replace(">","_").

**Comment by davek44** [comment]
Are these the SNP ID's in the 3rd column of the VCF?

**Comment by dborgesr** [comment]
Yup, exactly, for example chr1_g.93009425C>T_C_c6_seq, I simply replaced
the > where you change the output name.

**Comment by davek44** [comment]
Cool, I pushed a fix. Thanks
