### ISSUE TITLE
Exporting lua path 

### ISSUE THREAD

**Issue by dborgesr** [davek44/Basset#27]
So, I know that you've already bumped into the issue with exporting the LUA path aka:
export LUA_PATH="$BASSETDIR/src/?.lua;$LUA_PATH"
I'm still trying to figure out why it refuses to export it if stuck in the startup script.

But this is the last last stopping point in making an executable jupyter

**Comment by davek44** [comment]
After reviewing the README, I don't think I fully finished my thought when I was writing it. That export statement works well for me. Are you saying that it's not working, specifically inside jupyter notebooks?

**Comment by dborgesr** [comment]
So the export works if you spin up the Docker container and then manually export the variables, but the image won't work if you try to export the paths in the Dockerfile itself ie:
ENV LUA_PATH='$BASSETDIR/src/?.lua;$LUA_PATH'

The image still doesn't find lua. I think it might have something to do with length? or with the ? ? not sure...
