### ISSUE TITLE
wrong directory position

### ISSUE THREAD

**Issue by kwangjun14** [davek44/Basset#3]
when I run get_dnase.sh

# rearrange
mv egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/narrowPeak roadmap
rm -r egg2.wustl.edu
rmdir roadmap/hammock

on the script rmdir roadmap/hammock but  hammock is under roadmap/narrowPeack/
the script is wrong or Did i do something wrong ?

**Comment by davek44** [comment]
Hmm it works on OS X and CentOS. Perhaps wget is behaving differently on your system. Are you saying that the download from WUSTL creates the path egg2.wustl.edu/roadmap/data/byFileType/peaks/consolidated/narrowPeak/narrowPeak?

If you can manage to get the BED files into a directory called *roadmap*, and it should work from there. You can ignore the rmdir hammock line. I was just cleaning up.
