### ISSUE TITLE
Pre-computed model output as HDF5 

### ISSUE THREAD

**Issue by GabrielHoffman** [davek44/Basset#35]
I am trying to run basset_motifs.py, but it tries to access a files that doesn't exist.  If I don't specify the -d parameter:  
-d | model_hdf5_file | Pre-computed model output as HDF5 

then it tries to read a file: model_out.h5

Can you clarify what this file is, and what I should pass to the -d flag

Thanks, 
Gabriel

**Comment by davek44** [comment]
basset_motifs.py runs basset_motifs_predict.lua on the sequences first to generate model_out.h5. The option allows the user to specify that the torch code has already run and the file will already be there.

If the file isn't there, the torch code must have crashed. Could you run the torch command by itself and report any error information it produces? basset_motifs.py should print the torch command before running it here: https://github.com/davek44/Basset/blob/master/src/basset_motifs.py#L98
