### ISSUE TITLE
Training takes too long

### ISSUE THREAD

**Issue by laurajb** [davek44/Basset#38]
Hi! 
I am trying to train basset with my own data but I have been running into several issues with the gpus so I decided to try on the normal nodes in our cluster, however it's been running for 4 days now and I have far less sequences than the used amount in the paper so I don't know if there is any chance something went wrong without killing the process and now it's just halted or it really takes that long to run. 

All the best,
Laura

**Comment by davek44** [comment]
Hi Laura,

Unfortunately, you'll only be able to do very small analyses on CPUs. E.g you could score on the order of hundreds of SNPs or computed saturation mutagenesis maps for dozens of sequences. Anything beyond that really needs a GPU to speed things up.

Best,
Dave

**Comment by laurajb** [comment]
Hi Dave,

Thanks for your reply! Then I will try to get it running on the GPUs. Do you have any recommendations on how many GPU/cores/memory I should use for training a model with ~300,000 sequences? 

Best,
Laura

**Comment by davek44** [comment]
One GPU should be fine
