### ISSUE TITLE
Pre-trained Weights?

### ISSUE THREAD

**Issue by namheegordonkim** [davek44/Basset#39]
[https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4937568/](url)

In the above article, Basset is trained on ENCODE's DNAse-seq dataset. Are the pre-trained weights available somewhere, in case we want to replicate the analysis without training phase?

**Comment by davek44** [comment]
Pre-trained model weights are here: https://www.dropbox.com/s/rguytuztemctkf8/pretrained_model.th.gz
