### ISSUE TITLE
when run test.ipynb

### ISSUE THREAD

**Issue by kwangjun14** [davek44/Basset#4]
Hi
I trained and try to test your model.
on test.ipynb, 

model_file = '../data/models/pretrained_model.th'
seqs_file = '../data/encode_roadmap.h5'

but on my data direcotry, there is no encode_roadmap.h5 
there are
encode_roadmap.txt
encode_roadmap_act.txt
encode_roadmap.bed
Do I miss something to generate .h5 ? If so, where is the encoding part to make .h5 ?

**Comment by davek44** [comment]
I had changed *install_data.py* to remove some of these computationally-intensive steps. But you're right--it needs to be there for downstream analysis. I added back the steps to *install_data.py*. Grab the newest version, and re-run it to generate *encode_roadmap.h5*. Or you can just run the two commands at the bottom that I un-commented.
