### ISSUE TITLE
Nucleotide Order in Motif Heatmap Reversed

### ISSUE THREAD

**Issue by dg520** [davek44/Basset#42]
Hi David,

It seems the nucleotide order in motif heat map is reversed. On my end, they're printed as `T, G, C, A` from top to bottom. I've compared the weight matrix and the heat map matrix, both of the matrix suggest the correct order should be `A, C, G, T` from top to bottom.  A, C, G, T` is also the order in your tutorial outputs. 

This involves `ax.set_yticklabels('TGCA', rotation='horizontal')` in `basset_motifs.py`, and `ax_heat.yaxis.set_ticklabels('TGCA', rotation='horizontal')` in `basset_sat.py` and `basset_sat_vcf.py`.

Best,
Dadi

**Comment by davek44** [comment]
You're right, the order is flipped. Maybe a recent matplotlib changed how things work. I pushed fixes. Thanks for pointing this out!
