### ISSUE TITLE
Convolutional layers - padding and bias

### ISSUE THREAD

**Issue by remomomo** [davek44/Basset#45]
Hi Dave,

I have some technical questions for your original Basset model published id 2016.

Do the convolutions also use a bias parameter or not? Also, the convolutions are same-padded, right? 

cheers

**Comment by davek44** [comment]
Yes, the convolutions do use a bias parameter.

I'm not 100% familiar with the padding logic terminology. You can see exactly what's happening here in the code: https://github.com/davek44/Basset/blob/master/src/convnet.lua#L157-L164. In follow up work, I've found that the padding doesn't matter very much.
