### ISSUE TITLE
Prediction tasks specification

### ISSUE THREAD

**Issue by kmualim** [davek44/Basset#49]
Hi, 

Thank you for making the code available! 
The basset model has an output of 164, representing the predicted probability of accessibility in each cell type. 
Perhaps I might have missed it while reading the paper but I was wondering if the 164 celltypes are made available somewhere as I'd like to extract/use task-specific representations. 

Thanks!

**Comment by davek44** [comment]
I added a file called targets.txt that describes each of those cell types. The full path is *data/models/targets.txt*. If you want the BED files themselves, you *data/get_dnase.sh*
