### ISSUE TITLE
weights of a pretrained Basset model

### ISSUE THREAD

**Issue by osyafinkelberg** [davek44/Basset#58]
Hi!

I was wondering it it is possible to download weights of a pretrained Basset model compatible with a current PyTorch?

I found out [this file](https://www.dropbox.com/s/rguytuztemctkf8/pretrained_model.th.gz), but was not able to load it with the PyTorch.

Thank you very much!
Joseph

**Comment by davek44** [comment]
Hi Joseph,

Basset was trained in Torch, before PyTorch existed. I bet if you search
around, you could find some workflows to load Torch models into PyTorch.
Basset is also stored in the Kipoi repository, from which it can be used.
Finally, you might consider a newer PyTorch model with similar outputs like
Sei from Jian Zhou.

Best,
David

**Comment by osyafinkelberg** [comment]
Dear David,

Oh, I see. The Kipoi repository is indeed very helpful. Thank you so much!

Kind regards,
Joseph
