### ISSUE TITLE
basset_motifs_predict.lua does not work with GPU-trained model

### ISSUE THREAD

**Issue by jmrinaldi** [davek44/Basset#6]
basset_motifs_predict.lua expects a CPU-trained model, making basset_motifs.py non-functional for GPU-trained models.

Converting all model tensors to double solves problem, may want to add this functionality

**Comment by vagarwal87** [comment]
I believe I'm encountering this same error when attempting to make a continuous (rather than binary) prediction using basset_test.lua. Can you please explain which lines specifically you changed to fix the issue (was it in the convnet.lua module or somewhere else)?

**Comment by davek44** [comment]
Ah great. In general, moving models back and forth between the GPU and CPU can be tricky, so I don't want to make a ton of promises there. I added support for a GPU model to that script though.
