### ISSUE TITLE
Data preparation scripts should report progress

### ISSUE THREAD

**Issue by hammer** [davek44/Basset#9]
I enjoyed your talk today at NIPS! Our lab has been working with deep learning tools in biology as well, though we're working with [Keras/Theano and amino acid sequences](https://github.com/hammerlab/mhcflurry).

I'm giving Basset a spin and will file a few housekeeping issues. Please don't consider these issues to be demands or criticisms--they're more like notes to myself on ways I or our other [lab members](https://github.com/orgs/hammerlab/people) might contribute.

**Comment by hammer** [comment]
Logging or printing text is fine but may want to use [ProgressBar ](https://github.com/WoLpH/python-progressbar).

**Comment by hammer** [comment]
This request holds for both [preprocess_features.py](https://github.com/davek44/Basset/blob/master/src/preprocess_features.py) and [seq_hdf5.py](https://github.com/davek44/Basset/blob/master/src/seq_hdf5.py).

**Comment by davek44** [comment]
Another great tip. Will look into this soon
